### ISSUE TITLE
有没有考虑加入到opm资源库？

### ISSUE THREAD

**Issue by hzgoin** [kran/lua-resty-orm#4]
https://opm.openresty.org/

**Comment by kran** [comment]
~~它还有一个问题，事务处理的地方依赖`ngx.ctx`，如果在timer或者thread里使用事务，会有问题。目前我没有想到比较好的办法~~

事情貌似有了变化，刚才测试，竟然没有问题。但官方文档不再推荐用模块级变量来缓存`ngx.ctx`，所以这里需要修改一下。

**Comment by hzgoin** [comment]
我昨天查了文档，看到那段关于ngx.ctx的描述，在模块内声明为局部变量后生命周期会变成work级别的，一直在琢磨你说的问题是不是指这个…主要对lua也不是特别熟

**Comment by kran** [comment]
是这个。
